/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AmbientLight: typeof import('three')['AmbientLight']
  const BufferGeometry: typeof import('three')['BufferGeometry']
  const Color: typeof import('three')['Color']
  const DirectionalLight: typeof import('three')['DirectionalLight']
  const Float32BufferAttribute: typeof import('three')['Float32BufferAttribute']
  const Group: typeof import('three')['Group']
  const IcosahedronGeometry: typeof import('three')['IcosahedronGeometry']
  const MathUtils: typeof import('three')['MathUtils']
  const Mesh: typeof import('three')['Mesh']
  const MeshPhongMaterial: typeof import('three')['MeshPhongMaterial']
  const MeshPhysicalMaterial: typeof import('three')['MeshPhysicalMaterial']
  const OBJLoader: typeof import('three/examples/jsm/Addons.js')['OBJLoader']
  const OrbitControls: typeof import('three/examples/jsm/Addons.js')['OrbitControls']
  const PerspectiveCamera: typeof import('three')['PerspectiveCamera']
  const PointLight: typeof import('three')['PointLight']
  const Points: typeof import('three')['Points']
  const PointsMaterial: typeof import('three')['PointsMaterial']
  const RingGeometry: typeof import('three')['RingGeometry']
  const SRGBColorSpace: typeof import('three')['SRGBColorSpace']
  const Scene: typeof import('three')['Scene']
  const ShaderPass: typeof import('three/examples/jsm/Addons.js')['ShaderPass']
  const SpotLight: typeof import('three')['SpotLight']
  const TextureLoader: typeof import('three')['TextureLoader']
  const WebGLRenderer: typeof import('three')['WebGLRenderer']
}
